spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
cloudflare:
  r2:
    credentials:
      accessKey: dev
      secretKey: dev
    stack:
      auto: false
line:
  bot:
    channelToken: dev
    channelSecret: dev
    handler:
      path: /webhook